---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 1
  cleanup: post
  script:
    configMap:
      name: "k6-sample-stress-test"
      file: "test-influx.js"
  arguments: --out influxdb=http://influxdb:8086/k6
