apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: sample
spec:
  parallelism: 1
  cleanup: post
  script:
    configMap:
      name: sample-cm
      file: sample.js
  arguments: -o experimental-prometheus-rw
  runner:
    image: grafana/k6:latest-with-browser
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "https://prometheus.aws.legalmatch.com/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"
