apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-rw-test-cm
data:
  test-rw.js: |
    import { check, sleep } from 'k6';
    import remote from 'k6/x/remotewrite';
    
    export let options = {
        vus: 10,
        duration: '10s',
    };
    
    const client = new remote.Client({
        url: "http://localhost:9090/api/v1/write"
    });
    
    export default function () {
        let res = client.store([{
            "labels": [
                { "name": "__name__", "value": `my_cool_metric_${__VU}` },
                { "name": "service", "value": "bar" }
            ],
            "samples": [
                { "value": Math.random() * 100, }
            ]
        }]);
        check(res, {
            'is status 200': (r) => r.status === 200,
        });
        sleep(1)
    }